### PR TITLE
Console hide/show/is visible for Windows

### PR DESCRIPTION
**Pull request by subsoap**

### CODE REVIEW

**Comment by subsoap** [comment]
@AGulev Can we print with the macOS console in a useful way or are those dummy functions good enough?

**Comment by AGulev** [comment]
@subsoap I think dmlog will be suitable here
https://www.defold.com/ref/dmLog/

**Comment by subsoap** [comment]
@AGulev I don't have macOS computer handy at the moment if you have time could you add that for macOS build?

**Comment by AGulev** [comment]
@subsoap  yes, no problem

**Pull request merged**
