### PR TITLE
Clang 9 requirements

### PR DESCRIPTION
**Pull request by subsoap**
Changes requested by Defold team

### CODE REVIEW

**Comment by subsoap** [comment]
https://forum.defold.com/t/extender-server-ios-13-osx-10-15-clang-9/63569

:warning:Important: Set the build server in the Preferences:

https://build-stage.defold.com

I have not tested this yet but will soon.

**Comment by subsoap** [comment]
Tested building on 

https://build-stage.defold.com

and 

https://build.defold.com

Both work.

This change only disables this warning 

```
error: non-constant-expression cannot be narrowed from type 'LONG' (aka 'long') to 'float' in initializer list [-Wc++11-narrowing]
```

@dapetcu21 You can merge this if you do not think anything needs to be done to the code itself.

**Comment by dapetcu21** [comment]
I'd prefer to actually fix the errors instead of disabling the warning. I'll take a look this evening.

**Comment by dapetcu21** [comment]
Fixed by adding some casts

**Pull request closed without merging**
