### PR TITLE
add more function support for windows

### PR DESCRIPTION
**Pull request by chaosddp**
with example update

### CODE REVIEW

**Comment by chaosddp** [comment]
Also add clip_cursor and restore_cursor_clip on windows, when using clip_cursor, users have to restore it as cursor is shared resource. As i can image it should be restored then game window lost focus, or user closing game, so we need these event to restore.

**Comment by subsoap** [comment]
set_cursor_position can be a function to let user move cursor anywhere on screen

then have move_cursor_to to be relative to the current window client area, so it's x,y is relative to the client area and has a min/max of the client area

clip_cursor needs to clip the cursor to the client area it's currently allowed to go into the window area

also need dummy functions for html5/macOS

I can help with these if you want.

**Comment by chaosddp** [comment]
ok, then i will refine the clip_cursor and restore_cursor_clip function later too, as i think it is better to hold the original cursor position in our code, not return it to user.

**Comment by chaosddp** [comment]
added move_cursor_to to move cursor within current window area.

@subsoap does defold have event about window size changing? then we can update example to show how to clip cursor in right way.

**Comment by subsoap** [comment]
@chaosddp I'll test soon

https://www.defold.com/ref/window/ has window resize callback 

I also made https://github.com/subsoap/defwindow for when you want multiple call back functions for window events

**Comment by subsoap** [comment]
@chaosddp it's not right as it needs to be within the client area and constrained to it, there is not much general usefulness in setting cursor outside of the client area

2018-01-09-22_23_39-untitled-1- -33

**Comment by chaosddp** [comment]
@subsoap it is the same issue with your first implementation of is_mouse_inside_window when using the area from win32 api, i will have a try later after work

**Comment by chaosddp** [comment]
@subsoap i forgot that, after you clipping the cursor, windows will make sure cursor will always inside the window, even you give it a out of range pos.

**Comment by chaosddp** [comment]
@subsoap it should be work correctly now

**Comment by chaosddp** [comment]
@subsoap also with a set_client_size function for windows, you can have a try if it will fit you requirement in  #58.
And added new functions to macos to avoid build error, but without implementation

**Comment by dapetcu21** [comment]
@chaosddp I can take the macOS implementation. I actually needed the `set_client_size` functionality in my game.

**Comment by chaosddp** [comment]
@dapetcu21 Great! And next is the cursor, i will have a try this weekend.

**Comment by chaosddp** [comment]
Finally the set_cursor function is completed, now we have hardware cursor, this function supports .ani and .cur on Windows. 
To use this function you have to copy the cursor to a folder that we can access, i saved them to save folder in the example.
@subsoap, i think this is what you need :)
Also @dapetcu21 @AGulev

**Comment by dapetcu21** [comment]
I think I might have a bit of time this weekend to port this to macOS. Looked a bit over this and it looks fine, but I'd rename `set_client_size` to something else (maybe `set_view_size`), because the term "client area" is a windows-specific term.

**Comment by subsoap** [comment]
@chaosddp

Shoot! I lost track of this. I will test now.

**Comment by subsoap** [comment]
Tested and both clipping and custom cursor appear to work on Windows 10. Good job!

**Comment by subsoap** [comment]
@dapetcu21 changing to set_view_size sounds fine. Will need to document exactly what it means in the readme.

**Comment by dapetcu21** [comment]
I forked this and started hacking on the macOS part in the subsoap/cursors branch. Some stuff that I thought of along the way:

* I would also remove the bound checks for `move_mouse_to`. I think it might be valid for somebody to move the mouse outside his window by supplying negative coordinates. Is there any reason for this restriction? The user can do bound checking himself if that's what he wants.
* I'd also add a `get_view_size` as an analogue to `set_view_size`.

**Comment by subsoap** [comment]
Those sound fine.

**Comment by dapetcu21** [comment]
Made a PR with my changes over this at #60

**Pull request merged**
