### PR TITLE
Custom cursors and view size functions

### PR DESCRIPTION
**Pull request by dapetcu21**
This builds upon #57 and adds the following:
* Mac and HTML5 support for custom cursors
* System cursors, such as hand and I-beam cursors.
* `get_view_size()` / `set_view_size()` for all platforms.
* Made it so that passing `nil` instead of `-1` for `x` and `y` centers the window in the middle of the screen, since `-1` could be a valid coordinate value.
* Renamed `is_mouse_inside_window` to `is_mouse_in_view` to keep the "view" and "window" nomenclature consistent.
* Mac support for `move_mouse_to()` / `set_cursor_pos()`.
* Unified some `hide/show`, `clip/unclip` pairs in a single boolean setter. This makes usage easier and keeps our function count maintainable.
* More detailed docs

Please especially test the Windows part of this. I don't have access to a Windows PC for now, so I wrote code blindly.

### CODE REVIEW

**Comment by chaosddp** [comment]
I can add system cursor support  for windows later after vacation.

**Comment by dapetcu21** [comment]
Why did you close the PR? By the way. I added system cursor support for Windows as well. I just didn't test it.

**Comment by dapetcu21** [comment]
I think I'll also take a shot at cursor locking.

**Comment by subsoap** [comment]
I assume @chaosddp just clicked "close and comment" by mistake.

Great work with these changes and improvements!

On HTML5 on Windows with Chrome the hardware cursor goes invisible when clicking lock cursor. 

Does not build on for Windows currently

2018-02-18 04_43_32-defold editor 2 0 - defos

**Comment by chaosddp** [comment]
Sorry, my son clicked it:(

**Comment by dapetcu21** [comment]
Sorry. It should build now (still can't test, though). On HTML5 that's how the cursor locking API works. There's nothing I can do. Also, on macOS, when you lock the cursor you stop getting mouse moved events. I tried multiple approaches, but I think it has something to do with how Defold processes events.

**Comment by subsoap** [comment]
Tested Windows everything seems to work right.

**Comment by subsoap** [comment]
Should contact Defold team about macOS cursor lock not getting move events @britzl

**Comment by dapetcu21** [comment]
@subsoap Do you get move events on Windows when the cursor is locked? (I added a print so you should see them in the console)

**Comment by subsoap** [comment]
@dapetcu21 Yes
```
DEBUG:SCRIPT: FPS mouse dx, dy: 	1	1
DEBUG:SCRIPT: FPS mouse dx, dy: 	0	1
DEBUG:SCRIPT: FPS mouse dx, dy: 	0	-1
DEBUG:SCRIPT: FPS mouse dx, dy: 	-1	0
DEBUG:SCRIPT: FPS mouse dx, dy: 	2	2
DEBUG:SCRIPT: FPS mouse dx, dy: 	0	2
DEBUG:SCRIPT: FPS mouse dx, dy: 	2	7
DEBUG:SCRIPT: FPS mouse dx, dy: 	0	-1
DEBUG:SCRIPT: FPS mouse dx, dy: 	0	2
```

**Pull request merged**
