### PR TITLE
list of supported resolutions and other display info of monitor

### PR DESCRIPTION
**Pull request by chaosddp**
for windows

### CODE REVIEW

**Comment by AGulev** [comment]
@chaosddp Can I add macos and make some changes to your pull-request?

**Comment by AGulev** [comment]
I added macos support.
I made all the same way as in @chaosddp  code, but in my opinion would be better to use dmArray<DisplayInfo> array for data transfer from platform code, to crosplatform code. What do you think?

**Comment by chaosddp** [comment]
Done for Windows @AGulev, and i will have a try on the linux branch later.

**Comment by AGulev** [comment]
Cool! I'll do the same for macos today later.

**Comment by AGulev** [comment]
@chaosddp macOS changes are done

**Comment by chaosddp** [comment]
I will have a check if we can have Linux support later, then merge it.

**Comment by subsoap** [comment]
Was anyone with a Linux machine able to review this?

**Comment by dapetcu21** [comment]
This is good, but I think there isn't enough information to go on in there. For example, display placement and scaling is also useful. (For example, a use-case would be to center the window on a specific display with `set_window_size()`). See my proposal here: https://github.com/subsoap/defos/issues/87

I have some time this week to work on this and add all the extra info in those tables. I also have access to a Windows + Linux PC and I'll test on both

**Comment by dapetcu21** [comment]
So I added three new functions:
* `defos.get_displays()`, which gives you info about the current multi-display layout
* `defos.get_current_display_id()`, which tells you which display the game's window is currently on
* `defos.get_display_modes()`, which gives you all the available resolution modes for one display

I also went through the Linux implementation and filled in the gaps wherever I could.
I still have the Windows version of those functions to do before this is mergeable.

**Comment by dapetcu21** [comment]
The Window port should be done, so this can be merged. I also fixed up some other Windows bugs. We seem to be having a few other simple features in the backlog that I could have a go at while I'm at it.

Closes #87

**Comment by dapetcu21** [comment]
Aaand I think this should be enough for a release

**Pull request merged**
